### ISSUE TITLE
Question: Any plans for next release?

### ISSUE THREAD

**Issue by SamuelToh** [thlorenz/brace#110]
Hi guys,

it has been awhile since we have a release for brace. Just wondering if we will be seeing one anytime soon? 

Asking because we are currently working on a project which uses Brace and we would like to use some of the new features introduced in Ace 1.2.8 which is not included in the latest brace (since feb). 

A small release that includes the latest Ace upgrade by https://github.com/thlorenz/brace/pull/109 would be awesome. Not sure if this would help us or not but hopefully it will.

**Comment by thlorenz** [comment]
Yes, in the works, see https://github.com/thlorenz/brace/pull/109
