### ISSUE TITLE
how to use brace in es6

### ISSUE THREAD

**Issue by cookieY** [thlorenz/brace#117]
var ace = require('brace');
require('brace/mode/javascript');
require('brace/theme/monokai');

var editor = ace.edit('javascript-editor');
editor.getSession().setMode('ace/mode/javascript');
editor.setTheme('ace/theme/monokai');

ERROR:

Error in mounted hook: "TypeError: Cannot read property 'edit' of undefined"

**Comment by woowalker** [comment]
i got this problem, and i want to know how to fix it ? @cookieY

**Comment by longmajuxie** [comment]
me too

**Comment by cookieY** [comment]
@longmajuxie 
 u can try this

` 
const ace = require('brace')
 let editor = ace.edit('javascript-editor')
`

**Comment by longmajuxie** [comment]
[](url)

> @longmajuxie
> u can try this
> 
> ` const ace = require('brace') let editor = ace.edit('javascript-editor')`



> @longmajuxie
> u can try this
> 
> ` const ace = require('brace') let editor = ace.edit('javascript-editor')`

no working.
const ace = require('brace');
console.log('===', ace); 

when i use console.log,  display  === undefined. but i can  found brace in node_modules.

**Comment by cpkuo** [comment]
I had the same issue. For me, I had accidentally referenced ace.js from a script tag in my page.
