### ISSUE TITLE
Snippet order of appearance

### ISSUE THREAD

**Issue by fetacore** [thlorenz/brace#119]
I really like this library but I have two problems with it.
I am experimenting with custom snippets and language tool stuff but I find that the suggestions appear without alphabetical order or strict writing (if you have written 3 letters then regex will find any possible combination of the 3, which is not good ux when you use a code editor imo).
It would be awesome if you or somebody (even me if I find the solution) could ameliorate this feature.
Until now I could not reduce the problem to specific lines because there are regex everywhere and I have never worked with them (I always use str.search). A last question would be if you have pinpointed the event that triggers the appearance of snippets (I use latex so the snippets should appear on user input '\' ) but I cannot find it in the codebase.
Thank you very much and congratulations for the awesome repo.

**Comment by gokmen** [comment]
Hi @fetacore 

Thanks for the interest with the project but this repository only provides browserified compatible version of the Ace editor which is developing under https://github.com/ajaxorg/ace/ and you need to share the issues or questions with them.

Best,
