### ISSUE TITLE
Include a custom Mode

### ISSUE THREAD

**Issue by rngtng** [thlorenz/brace#14]
I tried to include a [custom mode](https://gist.github.com/rngtng/5ce656af7ba9b6ecffe9), but no luck I get following browserify errors:

```
Error: Cannot find module './folding/cstyle' from '/Users/tobi/Projects/js/vizard/js/lib'
Error: Cannot find module 'ace/lib/oop' from '/Users/tobi/Projects/js/vizard/js/lib'
```

I trief updating the  require path in various forms, but without luck. Any ideas how to resolve that? 

Thx Tobi

P.S: Custom Modes are explained here: http://ace.c9.io/#nav=higlighter

**Comment by sebas5384** [comment]
@rngtng could you share the working code? I'm trying to extend the markdown mode with PHP highlight rules, so I could use it with something like ```php

I tried with this code: https://github.com/ajaxorg/ace/wiki/Creating-or-Extending-an-Edit-Mode

Oh! I'm using brace with webpack, and it's working.

some help? :)

**Comment by rngtng** [comment]
@sebas5384 uh let me see if I can find it...

**Comment by rngtng** [comment]
@sebas5384 I think that's the file: https://github.com/rngtng/vizard/blob/master/js/lib/ace-mode-diagram.js

**Comment by sebas5384** [comment]
@rngtng thanks!! I'll try to implement that with webpack and see how it goes.
