### ISSUE TITLE
Please update the underlying ACE implementation

### ISSUE THREAD

**Issue by StoneCypher** [thlorenz/brace#148]
Hello and thanks for this high quality library

Would you please bump to 1.4.2?  There's some important changes and a language I'd like to pick up.

If you wrote out instructions on how to bump, we could submit bumps for you.

I joined your patreon at $10 to try to motivate you 😃 

Please have a good day.

**Comment by StoneCypher** [comment]
@thlorenz - or if you'd tell us how to do it, I'd do it

**Comment by tankbusta** [comment]
@StoneCypher Instructions on how to bump the version are included in the [README](https://github.com/thlorenz/brace#how-does-it-work) which is what was done in PR #139. Unfortunately, you'll have to fork the repository, bump the version in the updater script, and publish your fork if you want something simple like `yarn install brace` (unless @thlorenz comes back and automates this process). This is what I did to get 1.4.2

**Comment by StoneCypher** [comment]
ffffffffffffffffffffffffffffffffffffffffun.  (no i use npm because i'm allergic to new things.)

so it's the update script and that's it?  cool.  thanks, @tankbusta

**Comment by StoneCypher** [comment]
Got it.  Thanks again, destroyer of tanks.

https://github.com/thlorenz/brace/pull/151

**Comment by StoneCypher** [comment]
#153
