### ISSUE TITLE
CTRL + Z empty my content...

### ISSUE THREAD

**Issue by bbr-yp** [thlorenz/brace#167]
Hi

I'm using Brace via [jsonEditor](https://github.com/josdejong/jsoneditor.),
When you open an editor with content. 

If you press CTRL + Z. All the content is emptied...
In the same way, if you're editing a code... And cancel once too often... Everything gone..

Not a big deal because I can `redo` my `undo`.
But do you have a solution for fixing this?!
Thanks.

**Comment by nightwing** [comment]
This is a bug in jsonEditor, when initializing the editor, they need to either call `session.setValue` instead of `editor.setValue`, or call `session.getUndoManager().reset()` after the `setValue`

**Comment by bbr-yp** [comment]
Thanks for your answer :)
