### ISSUE TITLE
snippet + autocomplete support?

### ISSUE THREAD

**Issue by tanglx61** [thlorenz/brace#19]
First of all, great project!
I am running into a little trouble while trying to get snippets and autocomplete work. 
To simplify the problem, running the code below will show ```undefined``` for the output, in addition to generating an error ```GET file://.../brace/example/snippets/javascript.js net::ERR_FILE_NOT_FOUND```
```javascript
var ace = require('brace');
require('brace/mode/javascript');
require('brace/theme/monokai');

var langTools = require("brace/ext/language_tools");
console.log(langTools.addCompleter);
```
How would I go about solving this?
Thank you!

**Comment by piascikj** [comment]
I'm also wondering about this.  I don't think any extenstions work at this point.

**Comment by unknownexception** [comment]
I think it should be something like this:

```javascript
    require("brace/ext/language_tools");
    var langTools = ace.acequire("ace/ext/language_tools");
    this.editor.setOptions({enableBasicAutocompletion: true});

    var flowCompleter = {
        getCompletions: function(editor, session, pos, prefix, callback) {
           // your code
        }
    }
    langTools.addCompleter(flowCompleter);
```

First, you require file with browserify, then you use internal `ace` package manager. See source code.

**Comment by piascikj** [comment]
Worked like a charm!  Thanks

**Comment by thlorenz** [comment]
Can we close this? Have all questions been answered?

**Comment by thlorenz** [comment]
@unknownexception could you please add this information to the wiki? I created [a page](https://github.com/thlorenz/brace/wiki/Advanced:-Accessing-somewhat-hidden-ACE-features) for that purpose.

Thanks.
Also @piascikj if you have anything to add feel free to edit away in order for future users to find these kind of hidden features.

**Comment by piascikj** [comment]
In my opinion it's closed.  Thanks!

**Comment by unknownexception** [comment]
Added: https://github.com/thlorenz/brace/wiki/Advanced:-Accessing-somewhat-hidden-ACE-features . I'm working on simple IDE right now, will add useful examples later.

**Comment by thlorenz** [comment]
Thanks.
