### ISSUE TITLE
Vim Keyboard mode

### ISSUE THREAD

**Issue by VictorBjelkholm** [thlorenz/brace#21]
Starting looking for an text editor in Javascript, found Ace but couldn't use since not compatible with browserify. Started looking after CommonJS editors found this. Seems great but missing one feature which is why I actually chose Ace, it has Vim mode.

Starting trying to implement the Vim mode but after including just the keyboard file, it requires a lot of other smaller files which in their turn, requires other files.

So instead of just including all files, I was gonna ask first if this is wanted at all? Maybe I should find another editor with Vim mode and compatible with CommonJS from the start.

What you think?

**Comment by thlorenz** [comment]
This has been added and is demonstrated in JavaScript and CoffeeScript editors in `./example`.
