### ISSUE TITLE
Impossible to import the themelist

### ISSUE THREAD

**Issue by JannesMeyer** [thlorenz/brace#23]
Hi,

I have an options page, where I don't actually need an editor, I just want to get a list of supported themes, but I couldn't get it to work. Any help is appreciated.

## options.js
```javascript
var themeList = require('brace/ext/themelist');
console.log(themeList); // Uncaught ReferenceError: ace is not defined
```

Even including the whole editor didn't work:
```javascript
var ace = require('brace');
var themeList = require('brace/ext/themelist');
console.log(themeList); // {}
```

**Comment by thlorenz** [comment]
Not sure if this is supported.
Try something more similar to [this example](https://github.com/thlorenz/brace/blob/master/example/javascript-editor.js)

```js
var ace = require('brace');
require('brace/ext/themelist');
var themes = ace.acequire("ace/ext/themelist");
```

More info [in this wiki page](https://github.com/thlorenz/brace/wiki/Advanced:-Accessing-somewhat-hidden-ACE-features)

BTW feel free to add your example there once you get it to work.
