### ISSUE TITLE
Question about the HTML worker

### ISSUE THREAD

**Issue by jedfoster** [thlorenz/brace#24]
Is there a reason that the HTML worker is excluded from `build/workers.js`? (Or, more precisely, not explicitly _included_?)

I'm getting an error (`Cannot read property 'split' of undefined at Object.ace.define.exports.moduleUrl`) when I set the `mode` of my editor to `html`. After some debugging, I realized that the HTML worker is not included in the `worker` directory. This appears to be because HTML is not included in the `workers.supported` object. Is that an oversight, or did you intentionally leave it out for some reason?

I'm currently working on a PR to add Vim keybinding support (per #21, since I have the same need for it). I'd be happy to open an additional PR to address this HTML worker issue as well, but I wanted to ask first.

Thanks!

**Comment by thlorenz** [comment]
No reason, looks like you started taking care of it.

**Comment by jedfoster** [comment]
Thanks for this terrific project! Glad I could help to improve it.
