### ISSUE TITLE
Style `id` bug

### ISSUE THREAD

**Issue by kgryte** [thlorenz/brace#29]
See the following [line](https://github.com/thlorenz/brace/commit/1698c25c95858175700af09bcb51dfcafed19931#diff-168726dbe96b3ce427e7fedce31bb0bcR14828).

**Comment by thlorenz** [comment]
That's a bug in ace, so needs to be fixed there.
brace just patches ace to work with browserify.

**Comment by kgryte** [comment]
Filed an issue with ace.

**Comment by thlorenz** [comment]
Thanks.
