### ISSUE TITLE
can't require() in nodejs land

### ISSUE THREAD

**Issue by DelvarWorld** [thlorenz/brace#30]
`ReferenceError: window is not defined`

In my case i'm doing server side rendering of components. my component containing ace is included int the require() tree so it executes all requires, even though i'm not server-side rendering the ace component

**Comment by thlorenz** [comment]
brace is based on ace which only works in the browser. I doubt that will change, but feel free to file an issue with the ace editor.

**Comment by DelvarWorld** [comment]
Woah, hold on!! :smiley: I understand Ace is designed to work in the browser. Lots of NPM modules are:

    $ node

        > require('jquery')
            [Function]

        > require('three')
            { REVISION: '71', ... }

        > require('react')
            { Children: { map: [Function: mapChildren], ...

There's a few issues here:

**1** Fundamentally (more below), a module in `npm` should be requirable in node land. That's one of the reasons why I and others choose to use this library instead of copying Ace Javascript files into our project. 

**2** If the project errors at `require()` time, that means that simply requiring the project has side effects. Side effects are generally considered Bad™ when they happen when a function runs, and worse when they occur simply from including the presence of code.

**3** Strangely, Ace already [seems to guard against this](https://github.com/thlorenz/brace/blob/master/index.js#L42). So I'm not yet sure what's causing the window error. If it's something obvious I'll add a bug to the Ace editor as well.

**4** In these modern JS times we need libraries to be required in Node for server side rendering (from any library, but namely React). I don't mean that they need to render server side, but they need to be `required()` without error. Take this structure for example:

    let editor = require('Editor');
    let homepage = require('Homepage');
    ...
    render() {
        if( page === 'homepage' ) return homepage;
        if( page === 'editor' ) return editor;

Even if we're on a page that doesn't render the editor, **the editor will still be required**. If we try to execute this on the server to render our app to server, **it will fail** because simply requiring the editor will block load.

**5** In these modern JS times, we can [test our components](https://facebook.github.io/react/docs/test-utils.html) in isolated unit tests in NodeJS. Imagine I'm testing the homepage above. I can't, because simply requiring the homepage will require the editor. I can't even load the homepage first to stub out the editor, because I can't require it(!!).

Now I suppose the question centers around point 1. Whose responsibility is it to make the package "work" without side effects in Node? If you're maining this project simply by copying over the source files exactly 1:1 from Ace, then it's understandably more tricky because your modified code could get out of sync with the source. If you're making any hand modifications the code already, then it seems obvious to make minor changes to make it work in node.

**Comment by DelvarWorld** [comment]
The best friends club:
- https://github.com/ccampbell/mousetrap/issues/283
- https://github.com/zeroclipboard/zeroclipboard/issues/568
- https://github.com/thlorenz/brace/issues/30
