### ISSUE TITLE
Requiring anything but string fails

### ISSUE THREAD

**Issue by varemenos** [thlorenz/brace#36]
Ok, so the webapp I'm working on has 3 text editors, most of the configuration is the same for all of them but there are a few options that are passed via an object. My problem is that when I try to insert anything other than a string in require.

```js
var ace = require('brace');
require('brace/theme/monokai');
// works
```

```js
var ace = require('brace');
require(this.props.theme);
// `Uncaught Error: Cannot find module 'brace/theme/monokai'`
```

even this doesn't work:

```js
var ace = require('brace');
require('brace/theme/' + 'monokai');
// `Uncaught Error: Cannot find module 'brace/theme/monokai'`
```

**Comment by thlorenz** [comment]
Yep this is how browserify works - has to be statically analyzable.
This won't change, sorry.
