### ISSUE TITLE
cannot get Range to work

### ISSUE THREAD

**Issue by breakingco** [thlorenz/brace#37]
Hi, sorry if this is not an actual issue, but I can't figure it out from your documentation and have been trying for hours now...

I cannot require the ace Range object in order to use text selection in the browser. The nearest help I can get is per this post: http://stackoverflow.com/questions/26428573/ace-editor-set-text-selection in regards to the original Ace module.

Converting this into require('brace/range').Range or anything similar does not work - brace/range, brace/Range etc is not found.

I have been through the brace source code looking for all mentions of Range and trying to match up the require syntax for 'brace/mode' with the Range exports module I see there, but am having no success...can you help? Or does Brace not directly pass through all modules from Ace, and so anything to do with Range is missing?

**Comment by Azerothian** [comment]
I came across the same issue, this is what i did to solve it

var ace = require('brace');
var Range = ace.acequire('ace/range').Range;

**Comment by thlorenz** [comment]
@Azerothian mind adding this info to the wiki?
https://github.com/thlorenz/brace/wiki/Advanced:-Accessing-somewhat-hidden-ACE-features

**Comment by breakingco** [comment]
fixed! Thanks very much, I couldn't find the 'acequire' bit anywhere.

**Comment by adrian-moisa** [comment]
Thanks for sharing this answer. Saved my day :D
