### ISSUE TITLE
Doesn't work on server side. window is not defined

### ISSUE THREAD

**Issue by DWboutin** [thlorenz/brace#40]
Hi! I got this error with browserify:

```
node_modules/brace/index.js:1663
if (window.postMessage && !useragent.isOldIE) {
    ^

ReferenceError: window is not defined
    at /Users/mboutin2/Desktop/beverage/node_modules/brace/index.js:1663:5
    at lookup (/Users/mboutin2/Desktop/beverage/node_modules/brace/index.js:141:31)
    at _acequire (/Users/mboutin2/Desktop/beverage/node_modules/brace/index.js:75:23)
    at req (/Users/mboutin2/Desktop/beverage/node_modules/brace/index.js:138:24)
    at /Users/mboutin2/Desktop/beverage/node_modules/brace/index.js:18213:13
    at lookup (/Users/mboutin2/Desktop/beverage/node_modules/brace/index.js:141:31)
    at _acequire (/Users/mboutin2/Desktop/beverage/node_modules/brace/index.js:83:23)
    at Object.acequire (/Users/mboutin2/Desktop/beverage/node_modules/brace/index.js:93:26)
    at /Users/mboutin2/Desktop/beverage/node_modules/brace/index.js:18279:21
    at Object.<anonymous> (/Users/mboutin2/Desktop/beverage/node_modules/brace/index.js:18286:15)
```

**Comment by thlorenz** [comment]
What browser are you running this in. It should have a `window` object ;)

**Comment by DWboutin** [comment]
With browserify, the `window` object become `global`

**Comment by DWboutin** [comment]
You can check my repo: https://github.com/DWboutin/Beverage/tree/brace and run `npm install` after it, run `gulp`.

**Comment by thlorenz** [comment]
I doubt that browserify removes the `window` object from the context, that would break everything.
I don't have time to run your entire project. Please isolate the problem first, you might even run into the cause of the problem ;)

If anyone else has an idea please chime in @collaborators.

**Comment by DWboutin** [comment]
This is the problem

```
node_modules/brace/index.js:1663
if (window.postMessage && !useragent.isOldIE) {
    ^

ReferenceError: window is not defined
    at /Users/mboutin2/Desktop/beverage/node_modules/brace/index.js:1663:5
    at lookup (/Users/mboutin2/Desktop/beverage/node_modules/brace/index.js:141:31)
    at _acequire (/Users/mboutin2/Desktop/beverage/node_modules/brace/index.js:75:23)
    at req (/Users/mboutin2/Desktop/beverage/node_modules/brace/index.js:138:24)
    at /Users/mboutin2/Desktop/beverage/node_modules/brace/index.js:18213:13
    at lookup (/Users/mboutin2/Desktop/beverage/node_modules/brace/index.js:141:31)
    at _acequire (/Users/mboutin2/Desktop/beverage/node_modules/brace/index.js:83:23)
    at Object.acequire (/Users/mboutin2/Desktop/beverage/node_modules/brace/index.js:93:26)
    at /Users/mboutin2/Desktop/beverage/node_modules/brace/index.js:18279:21
    at Object.<anonymous> (/Users/mboutin2/Desktop/beverage/node_modules/brace/index.js:18286:15)
```

My project is VERY simple, it will take you about 1 or 2 minutes to run. I made this issue for your package development, i'll try another way then.

Thank you

**Comment by DWboutin** [comment]
Maybe a simple solution is to test `if(window !== undefined)` in your package!? And use global instead due to more and more people who will use Babel.

![capture d ecran 2015-11-02 a 16 56 27](https://cloud.githubusercontent.com/assets/1322006/10895522/c2a46eda-8182-11e5-98b8-d1b035172398.png)

**Comment by jedfoster** [comment]
I've looked at your project, and correct me if I'm wrong, but it looks like you are rendering your React app server-side. Node doesn't have a `window` object, which is why this is failing. You'll see if you run your `gulp browserify` task, that the client-side app JS compiles just fine; it's your `nodemon` and `src/server.js` that is blowing up. Has nothing to do with Babel.

IMO, it doesn't make any sense to try to render Ace server-side; it only has meaning on the client-side.

**Comment by thlorenz** [comment]
@jedfoster thanks for clarifying, that was my initial hunch as well which is why I asked what browser was used.
This has nothing to do with babel or whatever, one can't use packages server side that don't support that.

**Comment by DWboutin** [comment]
Ok, maybe it's Nodemon... I'm pretty new with the Universal Javascript's setup. But i found a solution... I added this in the begining of brace's index.js file. So it worked in my client side and don't load in my server side.

```
if(typeof window == "undefined"){
    return false;
}
```

**Comment by DWboutin** [comment]
To make it worked and don't have to modify your package I created a simple wrapper like this: 
```
if(typeof window != 'undefined'){
  module.exports = require('brace');
  require('brace/mode/javascript');
  require('brace/theme/monokai');
}
``` 

This is my whole wrapper. I need nothing more.

**Comment by thlorenz** [comment]
This wrapper doesn't belong in brace as its main use case is to work client side only.
There are other ways to work around this if your code also runs server side. Your wrapper is one and I'm happy you found a solution.
Also have a look at the [browser field](https://github.com/substack/browserify-handbook#browser-field).

**Comment by calepsol** [comment]
<Router onUpdate={() => window.scrollTo(0, 0)} history= {browserHistory}>
...
</Router>
