### ISSUE TITLE
How to use brace with webpack?

### ISSUE THREAD

**Issue by soulmachine** [thlorenz/brace#46]
This is more than a newbie question.

Even after I read the document I still have no idea how to use brace in webpack, it would be nice if someone could give me an example code snippet.

**Comment by jedfoster** [comment]
@soulmachine I recently converted a project that uses brace from Browserify to Webpack and other than configuring Webpack with my entries and outputs, I made no changes to application code. Brace doesn't care whether you use Browserify or Webpack. Is there a specific point that you are stuck on?

---

I use Webpack via Gulp, which results in a slightly more complex solution, but I have my reasons; some of this might not apply to your set up...

```javascript
// gulp/config.js

module.exports = {
  webpack: {
    entry: {
      app: src + '/js/app.coffee',
      editor: src + '/js/editor.coffee'
    },
    output: {
      path: __dirname + '/../public/js/',
      filename: '[name].js'
    },
    devtool: 'source-map',
    module: {
      loaders: [
        { test: /\.jade$/, loader: "jade-html" },
        { test: /\.coffee$/, loader: "coffee" }
      ]
    }
  },
}
```

```javascript
// gulp/tasks/webpack.js

var gulp = require('gulp');
var config = require('../config');
var webpack = require('webpack-stream');
var named = require('vinyl-named');

var entries = Object.keys(config.webpack.entry).map(function (key) {return config.webpack.entry[key]});

gulp.task('webpack', function(callback) {
  return gulp.src(entries)
  .pipe(named())
  .pipe(webpack(config.webpack))
  .pipe(gulp.dest(config.webpack.output.path));
});
```

```coffeescript
# client/js/editor.coffee

require 'brace'

# require 'brace/mode/css'
# require 'brace/mode/sass'
# require 'brace/mode/scss'
# require 'brace/mode/html'
# require 'brace/mode/haml'
# require 'brace/mode/jade'
require 'brace/mode/markdown'
# require 'brace/mode/textile'
# require 'brace/ext/emmet'
# require 'brace/keybinding/vim'

require 'brace/theme/tomorrow'

require "./edit"
# ... more app-specific `require`s
```

If I were using Webpack directly on the CLI, then all I'd need is the configuration block, with some modifications.

Hope that helps.

**Comment by greut** [comment]
@soulmachine nothing special. This file is compiled with babel like any other file.

```javascript
import ace from 'brace'
import 'brace/ext/statusbar'
import 'brace/ext/language_tools'
import 'tind/mode/xml'
import 'brace/theme/monokai'

const editor = ace.edit('marc-editor'),
const StatusBar = ace.acequire('ace/ext/statusbar').StatusBar

editor.statusbar = new StatusBar(editor, document.getElementById("status-bar"))
editor.getSession().setMode('ace/mode/xml')
editor.setTheme('ace/theme/xml')

//...
```

**Comment by chrisgeo** [comment]
One thing I've noticed, and hopefully I'm not hijacking this issue is: how can I compile the worker into the file do it doesn't load it asynchronously:

```javascript
define([
  'brace',
  'brace/mode/css',
  'brace/theme/monokai',
  'brace/worker/css'
], function () {});

```

When running webpack it still loads the file on demand for some reason.

**Comment by thlorenz** [comment]
Not made for webpack, but for browserify.
If you figure out how to do it anyways please provide a PR to add that information to the Readme.
Thanks.
