### ISSUE TITLE
upgrade ace 1.2.2 to 1.2.3

### ISSUE THREAD

**Issue by otanim** [thlorenz/brace#50]
ace editor has been upgraded, can you upgrade the brace ?

**Comment by thlorenz** [comment]
see [here](https://github.com/thlorenz/brace/issues/52#issuecomment-209214261)

**Comment by episodeyang** [comment]
I can't seem to find the release note for ace. Any pointers? Thanks! the npmjs packages are confusing.

**Comment by thlorenz** [comment]
nope, sorry .. ask in the ace repo.

**Comment by otanim** [comment]
thanks @thlorenz !
