### ISSUE TITLE
Need to update to newer version of ace

### ISSUE THREAD

**Issue by episodeyang** [thlorenz/brace#52]
I was having this issue. Looks like brace need to be updated to newer version.

https://github.com/ajaxorg/ace/issues/2943

**Comment by thlorenz** [comment]
Go ahead .. PRs appreciated .. instructions on how to upgrade are in the readme.

**Comment by episodeyang** [comment]
Will do!

**Comment by episodeyang** [comment]
I pulled from ace-build and it looks like the files have not changed. I was using 0.7.0. Updating to 0.8.0 fixed my problem. Closing this now.

Thanks for building this!
