### ISSUE TITLE
Emmet doesn't seem to work

### ISSUE THREAD

**Issue by webchaz** [thlorenz/brace#53]
Can you provide an example for how to include emmet.  When doing `require('brace/ext/emmet')` this appears to just disable tabbing.  Really appreciate any help.  Thanks.

**Comment by xiaokaike** [comment]
[how-to-add-emmet-support-in-ace-js-code-editor](http://stackoverflow.com/questions/17580711/how-to-add-emmet-support-in-ace-js-code-editor)
```js
require("ace/ext/emmet")
editor.setOption("enableEmmet", true)
```

**Comment by umireon** [comment]
emmet extension of ACE requires `window.emmet` to be loaded.
This is basically be achieved by loading emmet.js before using ACE as in [ACE's demo](https://github.com/ajaxorg/ace/blob/master/demo/emmet.html).
With `brace` and `browserify`, you can simply export `emmet` to `window` by following code:

```js
window.emmet = require('emmet')
var ace = require('brace')
require('ace/ext/emmet')
ace.acequire('ace/ext/emmet')
editor.setOption('enableEmmet', true)
// what you want
// ...
```
