### ISSUE TITLE
Ctrl-F to search is broken

### ISSUE THREAD

**Issue by ratiotile** [thlorenz/brace#62]
possibly related to #58 
Using brace 0.8.0, trying to search by pressing ctrl-f throws errors:

    ext-searchbox.js:1 Uncaught SyntaxError: Unexpected token <
    brace:10749 Uncaught TypeError: Cannot read property 'Search' of undefined

the ext-searchbox.js loaded by the browser looks like html, which explains the syntax error.

brace:10749 is `config.loadModule("ace/ext/searchbox", function(e) {e.Search(editor)})`
so the error in ext-searchbox.js is making it return undefined.

**Comment by ratiotile** [comment]
Needed to `require('brace/ext/searchbox')`

**Comment by AStoker** [comment]
Did you have to modify your code, or was this done in the source code?

**Comment by ratiotile** [comment]
I needed to `require('brace/ext/searchbox')` in my application that uses brace.
