### ISSUE TITLE
Could you please fix the bug with the none English input(like Chinese)?

### ISSUE THREAD

**Issue by andyforever** [thlorenz/brace#66]
[ace issue #3099](https://github.com/ajaxorg/ace/pull/3099)
Thanks

**Comment by thlorenz** [comment]
Needs to be fixed in ace. once that's done please upgrade the ace version here, using the [script outlined here](https://github.com/thlorenz/brace#how-does-it-work) and submit a PR.
Thanks

Closing since the problem itself can't be fixed here.
