### ISSUE TITLE
Getting brace to work with tern.js

### ISSUE THREAD

**Issue by mattduffield** [thlorenz/brace#70]
First off, awesome tool!

I am trying to get tern.js work with brace and I am having trouble getting it to work. Is there a way to have the following:

https://github.com/sevin7676/ace/tree/master/lib/ace/tern

Available for consumption in brace? I don't know how to port these files over to what brace needs.

**Comment by thlorenz** [comment]
I think it should be possible, but the update scripts would need to be modified afaik.
I've got no bandwidth for that however so someone else would need to take that on.

**Comment by mattduffield** [comment]
If you could let me know what needs to be modified, I would be happy to try.

**Comment by thlorenz** [comment]
You'd need to modify the update scripts [explained in the readme](https://github.com/thlorenz/brace#how-does-it-work)

**Comment by mattduffield** [comment]
Thanks for the update! Closing the issue.
