### ISSUE TITLE
Gutter problem in Chrome

### ISSUE THREAD

**Issue by MMRandy** [thlorenz/brace#71]
We started experiencing a strange problem with the ACE Editor in our web app.  The line numbers would not fully rendering themselves, errors are thrown during gutter cell creation, etc.  I thought the problem was related to specific machine/environment issues...but have since ruled that out when others began having the same issues.  I then started digging into the problem and saw that it seems to be a problem with the dom.createElement() method in the index.js, where sometimes this function returns a null...which then gets passed down to the appendChild method during the cell.update method, which in turn blows up trying to call the this method on a null object.  

In addition, I uninstalled latest stable version of Chrome to ensure it's not something specific to my machine...and then installed a bunch of different versions of Chrome...and it seems this problem manifests itself in version 54 and 55, but works fine on others.  Here are the specifics.

    - Does Not Work
        - Version 54.0.2840.98 stable current (64-bit)
        - Version 54.0.2840.71 stable older (64-bit)
        - Version 55.0.2883.59 beta (64-bit)
    - Works
        - Version 57.0.2931.0 canary (64-bit)
        - Version 56.0.2924.3 dev (64-bit)
        - Version 53.0.2785.116 (64-bit)
        - Version 51.0.2704.106 stable older (64-bit)

Attached is an image that should capture the specifics of what I'm mentioning.  Could this be a race condition when rendering a large number of cells?  What would cause the dom.createElement to return null?  

<img width="1420" alt="screen shot 2016-11-26 at 2 59 13 pm" src="https://cloud.githubusercontent.com/assets/1464174/20649072/a94fe4c4-b484-11e6-8208-464d81c1a510.png">

Lastly, to make this even harder to troubleshoot, others in the office can run the same stable version of Chrome as the others of us having this issue, and it works fine....¯\_(ツ)_/¯

This is a tough one to figure out...

Thanks.

**Comment by thlorenz** [comment]
Issue with ace, please file the issue there.
