### ISSUE TITLE
 chinese input have problem

### ISSUE THREAD

**Issue by JarvisYang** [thlorenz/brace#72]
The lastest version ace fix this bug
<https://github.com/ajaxorg/ace/issues/3099>
<https://github.com/hoge1e3/jslesson/commit/7da745df681ca0a8ac3304122b89ea87be44a813>

**Comment by thlorenz** [comment]
> The lastest version ace fix this bug

OK then I invite you to run the update script as [explained](https://github.com/thlorenz/brace#how-does-it-work) and get it into brace by submitting a pull request.
Please make sure to run `update-ts.js` as well as `update.js`.

**Comment by thlorenz** [comment]
Should be addressed with out brace update (still in progress).
