### ISSUE TITLE
"modes" throw errors

### ISSUE THREAD

**Issue by VinzentE** [thlorenz/brace#78]
When I add the component to my app, it shows me 2 error messages without any further details.
* mode-java.js:1 Uncaught SyntaxError: Unexpected token <
* java.js:706 Uncaught TypeError: Cannot read property 'CstyleBehaviour' of undefined

Both somehow seem to be related to 
../ brace / modes / {mode}.js

Is that a bug or am I missing s.th.?

**Comment by thlorenz** [comment]
Looks like a problem with your templating engine .. definitely not related to brace, so closing.
