### ISSUE TITLE
how can i prettify JSON?

### ISSUE THREAD

**Issue by GreenMelon** [thlorenz/brace#79]
what i get: "{"name":"caigua","age":24,"married":false}"

and what i want: 
![image](https://cloud.githubusercontent.com/assets/13148281/23648239/c412cdb6-0354-11e7-93f7-d43f2e522812.png)

**Comment by GreenMelon** [comment]
I have got the answer~

**Comment by Jonarod** [comment]
Could you elaborate? I have the same problem here...
Thanks !

**Comment by GreenMelon** [comment]
```javascript
const value = '{"name":"caigua","age":24,"favor":["nba","writting"]}';
this.editor.setValue(JSON.stringify(JSON.parse(value), null, '\t'));
```
sorry for giving answer late
