### ISSUE TITLE
Focus causing page to scroll to top

### ISSUE THREAD

**Issue by Mystify** [thlorenz/brace#80]
I have a react application that is using a bootstrap modal. (not sure if the modal is important or not)
When the editor is off the bottom of the screen because of the height of dialog, when the editor get's focus, the entire modal dialog/page scrolls to the top of the screen, putting the editor off the bottom of the screen.

I tracked the problem down to the following line:
line 1959 in index.js: text.style.position = "fixed";

If I comment this line out, the scrolling to the top of the page seems to stop, and I can not detect any unusual or bad side effects.

Here is the full block of code:
```
    this.focus = function() {
        if (tempStyle) return text.focus();
        var top = text.style.top;
        text.style.position = "fixed";     // <--- this line causes the page to scroll to the top when the editor get's focus
        text.style.top = "0px";
        text.focus();
        setTimeout(function() {
            text.style.position = "";
            if (text.style.top == "0px")
                text.style.top = top;
        }, 0);
    };
```

If it's possible, can this be looked into and fixed in the next update? I have it commented out now in my code, but if I ever do an update or re-install I will lose the change. I am also not sure what the side effects, if any, would be.

Cheers, and good work!
Dave

**Comment by thlorenz** [comment]
This is an issue with ace, brace just wraps it.
Please file the issue there

**Comment by summertian4** [comment]
This problem has not been solved and still appears on Chrome

**Comment by summertian4** [comment]
How can I fix it

**Comment by Ultraseamus** [comment]
I ended up at the same line of code debugging the same issue. Ace appears to have corrected the issue a year ago https://github.com/ajaxorg/ace/commit/bd3c511fd48bb50ed6e621ab7406b4e1f6dc6f08.

with:

this.focus = function() {
        if (tempStyle || HAS_FOCUS_ARGS || this.$focusScroll == "browser")
            return text.focus({ preventScroll: true });

HAS_FOCUS_ARGS is true for current versions of Chrome. So it will avoid running the problematic parts of that function.

There's an open request to update to ace version 1.4.2 which would include this fix.

**Comment by ivanpenchev** [comment]
I ended up with a workaround solution by using the `onFocus` property and the [`scrollIntoView` method](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) like this.

`onFocus={e => document.getElementById('my-editor').scrollIntoView()}`

This does seem to do the trick, even though it makes a weird initial selection inside the editor sometimes.
