### ISSUE TITLE
Minify the brace library size

### ISSUE THREAD

**Issue by friedpine** [thlorenz/brace#92]
I have a simple application which wants a small javascript files. After webpack, the bundle of brace application page is more than 5M in size. How can I minify it? Can I remove most of the mode and styles and keep the most common poptions like JOSN, R, python? And hopefully how much extra size can we remove by this way?

**Comment by thlorenz** [comment]
This is a more general question about the minify build step, please ask in stackoverflow. Not sure how webpack works, but it shouldn't include anything you aren't `require`ing.
